### ISSUE TITLE
i'm lost on "TypeError: Cannot read properties of null (reading 'getMonth')"

### ISSUE THREAD

**Issue by RobotWF** [datakurre/carrot-rcc#16]
I'm lost on running a robot using carrot-rcc
i get this error **"TypeError: Cannot read properties of null (reading 'getMonth')"** and do not understand where it is comming from.
Is it in my robot? Is it the BPMN file? I suppose not because it is running and returns OK

So the question is: Is the error related to carrot-rcc, and can we solve it?

==============================================================================
rcc-tasks-41rqrH                                                              
==============================================================================
rcc-tasks-41rqrH.Worker :: Tasks.robot perform checks to see if submodules ...
==============================================================================
Scrape Phone Book And Split Into Work Items                           | PASS |
------------------------------------------------------------------------------
rcc-tasks-41rqrH.Worker :: Tasks.robot perform checks to see if su... | PASS |
1 task, 1 passed, 0 failed
==============================================================================
rcc-tasks-41rqrH                                                      | PASS |
1 task, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\brian\AppData\Local\Temp\rcc-tasks-41rqrH\output\output.xml
Log:     C:\Users\brian\AppData\Local\Temp\rcc-tasks-41rqrH\output\log.html

[SNIP]

OK.
TypeError: Cannot read properties of null (reading 'getMonth')

**Comment by datakurre** [comment]
@RobotWF It's carrot-rcc issue. Fixed in version control, but not released. I'll do a release later today.

**Comment by datakurre** [comment]
@RobotWF I pushed carrot-rcc==0.6.1 with related fixes.
